USE [master]
GO
/****** Object:  Database [POO Proiect]    Script Date: 21.04.2022 01:28:49 ******/
CREATE DATABASE [POO Proiect]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'POO Proiect', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\POO Proiect.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'POO Proiect_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\POO Proiect_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [POO Proiect] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [POO Proiect].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [POO Proiect] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [POO Proiect] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [POO Proiect] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [POO Proiect] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [POO Proiect] SET ARITHABORT OFF 
GO
ALTER DATABASE [POO Proiect] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [POO Proiect] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [POO Proiect] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [POO Proiect] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [POO Proiect] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [POO Proiect] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [POO Proiect] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [POO Proiect] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [POO Proiect] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [POO Proiect] SET  DISABLE_BROKER 
GO
ALTER DATABASE [POO Proiect] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [POO Proiect] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [POO Proiect] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [POO Proiect] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [POO Proiect] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [POO Proiect] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [POO Proiect] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [POO Proiect] SET RECOVERY FULL 
GO
ALTER DATABASE [POO Proiect] SET  MULTI_USER 
GO
ALTER DATABASE [POO Proiect] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [POO Proiect] SET DB_CHAINING OFF 
GO
ALTER DATABASE [POO Proiect] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [POO Proiect] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [POO Proiect] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [POO Proiect] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'POO Proiect', N'ON'
GO
ALTER DATABASE [POO Proiect] SET QUERY_STORE = OFF
GO
USE [POO Proiect]
GO
/****** Object:  Table [dbo].[Canale]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Canale](
	[ID_Canal] [int] IDENTITY(1,1) NOT NULL,
	[Nume_Canal] [nvarchar](30) NOT NULL,
	[Descriere] [text] NOT NULL,
	[Owner] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Canale] PRIMARY KEY CLUSTERED 
(
	[ID_Canal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Conversatii]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Conversatii](
	[ID_Conversatie] [int] IDENTITY(1,1) NOT NULL,
	[Utilizator1] [nvarchar](20) NOT NULL,
	[Utilizator2] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Conversatii] PRIMARY KEY CLUSTERED 
(
	[ID_Conversatie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fisiere]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fisiere](
	[ID_Fisier] [int] IDENTITY(1,1) NOT NULL,
	[Nume_Fisier] [nvarchar](30) NOT NULL,
	[Nume_Autor] [nvarchar](30) NOT NULL,
	[Timp_Incarcare] [bigint] NOT NULL,
	[ID_Canal] [int] NOT NULL,
 CONSTRAINT [PK_Fisiere] PRIMARY KEY CLUSTERED 
(
	[ID_Fisier] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Membri_Canale]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Membri_Canale](
	[ID_Canal_Membru] [int] IDENTITY(1,1) NOT NULL,
	[ID_Canal] [int] NOT NULL,
	[ID_Utilizator] [int] NOT NULL,
 CONSTRAINT [PK_Membri_Canale] PRIMARY KEY CLUSTERED 
(
	[ID_Canal_Membru] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mesaje_Canale]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mesaje_Canale](
	[ID_Mesaj] [int] IDENTITY(1,1) NOT NULL,
	[Expeditor] [nvarchar](30) NOT NULL,
	[Text] [text] NOT NULL,
	[Titlu] [nvarchar](30) NOT NULL,
	[Timp_incarcare] [bigint] NOT NULL,
	[ID_Canal] [int] NOT NULL,
 CONSTRAINT [PK_Mesaje] PRIMARY KEY CLUSTERED 
(
	[ID_Mesaj] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mesaje_Conversatii]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mesaje_Conversatii](
	[ID_Mesaj] [int] IDENTITY(1,1) NOT NULL,
	[Mesaj] [text] NOT NULL,
	[ID_Conversatie] [int] NOT NULL,
	[Emitator] [nvarchar](30) NOT NULL,
	[Timp_incarcare] [bigint] NOT NULL,
 CONSTRAINT [PK_Mesaje_Conversatii] PRIMARY KEY CLUSTERED 
(
	[ID_Mesaj] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Notificari]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notificari](
	[Notificare] [text] NOT NULL,
	[Timp_incarcare] [bigint] NOT NULL,
	[ID_Destinatar] [int] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Utilizatori]    Script Date: 21.04.2022 01:28:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Utilizatori](
	[ID_Utilizator] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](20) NOT NULL,
	[Parola] [nvarchar](20) NOT NULL,
	[Email] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_Utilizatori] PRIMARY KEY CLUSTERED 
(
	[ID_Utilizator] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fisiere]  WITH CHECK ADD  CONSTRAINT [FK1] FOREIGN KEY([ID_Canal])
REFERENCES [dbo].[Canale] ([ID_Canal])
GO
ALTER TABLE [dbo].[Fisiere] CHECK CONSTRAINT [FK1]
GO
ALTER TABLE [dbo].[Membri_Canale]  WITH CHECK ADD  CONSTRAINT [FK_Membri_Canale_Canale] FOREIGN KEY([ID_Canal])
REFERENCES [dbo].[Canale] ([ID_Canal])
GO
ALTER TABLE [dbo].[Membri_Canale] CHECK CONSTRAINT [FK_Membri_Canale_Canale]
GO
ALTER TABLE [dbo].[Membri_Canale]  WITH CHECK ADD  CONSTRAINT [FK_Membri_Canale_Utilizatori] FOREIGN KEY([ID_Utilizator])
REFERENCES [dbo].[Utilizatori] ([ID_Utilizator])
GO
ALTER TABLE [dbo].[Membri_Canale] CHECK CONSTRAINT [FK_Membri_Canale_Utilizatori]
GO
ALTER TABLE [dbo].[Mesaje_Canale]  WITH CHECK ADD  CONSTRAINT [FK2] FOREIGN KEY([ID_Canal])
REFERENCES [dbo].[Canale] ([ID_Canal])
GO
ALTER TABLE [dbo].[Mesaje_Canale] CHECK CONSTRAINT [FK2]
GO
ALTER TABLE [dbo].[Mesaje_Conversatii]  WITH CHECK ADD  CONSTRAINT [FK_Mesaje_Conversatii_Conversatii] FOREIGN KEY([ID_Conversatie])
REFERENCES [dbo].[Conversatii] ([ID_Conversatie])
GO
ALTER TABLE [dbo].[Mesaje_Conversatii] CHECK CONSTRAINT [FK_Mesaje_Conversatii_Conversatii]
GO
ALTER TABLE [dbo].[Notificari]  WITH CHECK ADD  CONSTRAINT [FK_Notificari_Utilizatori] FOREIGN KEY([ID_Destinatar])
REFERENCES [dbo].[Utilizatori] ([ID_Utilizator])
GO
ALTER TABLE [dbo].[Notificari] CHECK CONSTRAINT [FK_Notificari_Utilizatori]
GO
USE [master]
GO
ALTER DATABASE [POO Proiect] SET  READ_WRITE 
GO
